name: Postman Collection Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # allows manual trigger
  schedule:
    - cron : 28 10 * * * # this is UTC timezone 
    - cron : 00 14 * * * # this is UTC timezone
    - cron : 00 06 * * 1-5  # this is UTC timezone Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubantu-latest 

    steps:
      - name: checkout the code
        uses: actions/checkout@v6-beta

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install newman and Html-extra globally
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
              newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra

      - name: Newman Report
        if: always() # ensure that the archive executed irrespective whether the previous test are passed or not.
        uses: actions/upload-artifact@v4.6.2
        with:
            name: Newman Report
            path: newman/*.html
      
  
